// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aznvimopmndgsrijicrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6bnZpbW9wbW5kZ3NyaWppY3JkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgzMzA0NDQsImV4cCI6MjA1MzkwNjQ0NH0.S4nQE0vkgKsxbsMKxlhDnCsioLYgJUW6LMSf6SrSYe4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);